source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '9.0'
use_frameworks!

target 'SwiftExpandExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SwiftExpand', :path => '../'

  # Pods for SwiftExpandExample

end
